---
repos:
  - repo: https://github.com/psf/black.git
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(tests\/hooks-abort-render\/hooks|docs\/HelloCookieCutter1)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.960'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1
    hooks:
      - id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs.
        entry: python -m doc8
        language: python
        files: \.rst$
        require_serial: true
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.7.9
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-docstrings
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.6.0
  #   hooks:
  #     - id: bandit
  #       args: [--ini, .bandit]
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.2.4
  #   hooks:
  #   - id: python-safety-dependencies-check