name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: tests
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
      - name: Postrelease
        run: >-
          make ZEST_RELEASER_POSTRELEASE_OPTIONS=--no-input postrelease
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add pyproject.toml CHANGES.md
          git commit -m"Post release: back to development."
          git push
